sudo: false
addons:
  apt_packages:
    - xorg-dev
language: go
go:
  - 1.9
  - tip
  - master
matrix:
  allow_failures:
    - go: master
  fast_finish: true
install:
  - go get -d -t ./...
  - go get github.com/mattn/goveralls
  - git clone https://github.com/glfw/glfw && mkdir build && cd build && cmake ../glfw && make -j4 && sudo make install
script:
  - go test
  - cd example/
  - go build
  - $GOPATH/bin/goveralls -service=travis-ci